"""intial_setup

Revision ID: 5daff7687149
Revises: 
Create Date: 2026-02-25 14:16:51.003755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '5daff7687149'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("SET search_path TO public;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ceo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('c_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('senior_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.Integer(), nullable=True),
    sa.Column('subsector', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('network_status', sa.String(), nullable=True),
    sa.Column('contact_status', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('call_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('people_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['public.calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('interviewee_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_insight_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('current_title', sa.Text(), nullable=True),
    sa.Column('current_company', sa.Text(), nullable=True),
    sa.Column('seniority_level', sa.Text(), nullable=True),
    sa.Column('industry_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_experience_estimate', sa.Numeric(), nullable=True),
    sa.Column('career_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leadership_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transformation_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('private_equity_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notable_achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('searchable_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('has_pe_experience', sa.Boolean(), nullable=True),
    sa.Column('transformation_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['call_insight_id'], ['public.call_insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_interviewee_profiles_has_pe_experience'), 'interviewee_profiles', ['has_pe_experience'], unique=False, schema='public')
    op.execute("""
        ALTER TABLE public.interviewee_profiles 
        ALTER COLUMN embedding TYPE public.vector(1536) USING embedding::public.vector(1536);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_interviewee_profiles_has_pe_experience'), table_name='interviewee_profiles', schema='public')
    op.drop_table('interviewee_profiles', schema='public')
    op.drop_table('call_insights', schema='public')
    op.drop_table('companies', schema='public')
    op.drop_table('calls', schema='public')
    # ### end Alembic commands ###
