"""baseline

Revision ID: ed9586691ad9
Revises: 
Create Date: 2026-02-12 19:04:30.547218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9586691ad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notch'
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ceo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('c_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('senior_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.Integer(), nullable=True),
    sa.Column('subsector', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('network_status', sa.String(), nullable=True),
    sa.Column('contact_status', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='notch'
    )
    op.create_table('call_insights',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('people_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['notch.calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id'),
    schema='notch'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_insights', schema='notch')
    op.drop_table('companies', schema='notch')
    op.drop_table('calls', schema='notch')
    # ### end Alembic commands ###
